// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openAIGRPC.proto

package com.grpc;

public interface ApiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.ApiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string request_body = 2;</code>
   * @return The requestBody.
   */
  java.lang.String getRequestBody();
  /**
   * <code>string request_body = 2;</code>
   * @return The bytes for requestBody.
   */
  com.google.protobuf.ByteString
      getRequestBodyBytes();

  /**
   * <code>string api_key = 3;</code>
   * @return The apiKey.
   */
  java.lang.String getApiKey();
  /**
   * <code>string api_key = 3;</code>
   * @return The bytes for apiKey.
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();
}
