// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openAIGRPC.proto

package com.grpc;

public interface ApiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.ApiResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>map&lt;string, string&gt; response_headers = 2;</code>
   */
  int getResponseHeadersCount();
  /**
   * <code>map&lt;string, string&gt; response_headers = 2;</code>
   */
  boolean containsResponseHeaders(
      java.lang.String key);
  /**
   * Use {@link #getResponseHeadersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getResponseHeaders();
  /**
   * <code>map&lt;string, string&gt; response_headers = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getResponseHeadersMap();
  /**
   * <code>map&lt;string, string&gt; response_headers = 2;</code>
   */
  /* nullable */
java.lang.String getResponseHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; response_headers = 2;</code>
   */
  java.lang.String getResponseHeadersOrThrow(
      java.lang.String key);
}
