// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openAIGRPC.proto

package com.grpc;

public final class ApiServiceGRPC {
  private ApiServiceGRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_ApiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_ApiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_ApiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_ApiResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_ApiResponse_ResponseHeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_ApiResponse_ResponseHeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020openAIGRPC.proto\022\010com.grpc\"@\n\nApiReque" +
      "st\022\013\n\003url\030\001 \001(\t\022\024\n\014request_body\030\002 \001(\t\022\017\n" +
      "\007api_key\030\003 \001(\t\"\231\001\n\013ApiResponse\022\014\n\004data\030\001" +
      " \001(\014\022D\n\020response_headers\030\002 \003(\0132*.com.grp" +
      "c.ApiResponse.ResponseHeadersEntry\0326\n\024Re" +
      "sponseHeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\0012J\n\nApiService\022<\n\013SendRequest\022" +
      "\024.com.grpc.ApiRequest\032\025.com.grpc.ApiResp" +
      "onse\"\000B\037\n\010com.grpcB\016ApiServiceGRPCP\001\210\001\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpc_ApiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_ApiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_ApiRequest_descriptor,
        new java.lang.String[] { "Url", "RequestBody", "ApiKey", });
    internal_static_com_grpc_ApiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_ApiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_ApiResponse_descriptor,
        new java.lang.String[] { "Data", "ResponseHeaders", });
    internal_static_com_grpc_ApiResponse_ResponseHeadersEntry_descriptor =
      internal_static_com_grpc_ApiResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_grpc_ApiResponse_ResponseHeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_ApiResponse_ResponseHeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
